import 'package:test/test.dart';

import '../../../scikit/preprocessing/stemming/PorterStemmer.dart';


void main() {
  group("Porter stemmer", () {
    test("Test 1",(){
      PorterStemmer ps = PorterStemmer();
      String text = "The young botanist was fascinated by the collection of plants she had gathered during her research expedition. Observing the natural variation within different plant species, she noted that many characteristics were evolving uniquely, and she hypothesized that environmental changes were contributing significantly. By comparing diverse specimens, she aimed to better understand the relationships between evolution, adaptation, and biodiversity. Analyzing the developmental pathways of each plant, she began categorizing them based on similar attributes. Her colleagues, equally intrigued, assisted by meticulously documenting each observation, ensuring that all information was preserved accurately for future reference. They believed their collaborative efforts would eventually enhance the understanding of botanical sciences, leading to potential breakthroughs in agricultural sustainability.Throughout the process, they also considered the broader implications of their work, pondering how their findings could influence climate change policies. The potential applications of their research seemed vast, stretching from educating communities to rethinking agricultural practices that were unsustainable. Their motivation was driven not only by scientific curiosity but also by a profound sense of responsibility for preserving ecological balance.The expedition had its challenges, of course. Days were spent enduring extreme weather conditions, hiking through dense underbrush, and navigating tricky terrain. Each encounter with the natural world brought forth its own set of difficulties, yet the botanist and her team remained undeterred. Every new discovery, whether it was a previously unknown fungus or a plant displaying an unusual pattern of growth, reignited their determination.As their journey continued, they compiled a vast repository of information. This collection became a valuable database that could potentially aid other scientists in addressing questions about species distribution, resilience, and adaptation in the face of environmental pressures. They envisioned a future where the fruits of their labor would inspire new generations of researchers to approach the natural world with a similar blend of curiosity and reverence.Ultimately, the botanist believed that the most meaningful contribution they could make was to foster an understanding of how interconnected all living systems were. She hoped that their expedition, despite its hardships, would plant the seeds of knowledge that could help society navigate an uncertain ecological future. Their work emphasized the importance of resilience, adaptability, and informed stewardship of the environment, which they saw as essential for the long-term health of our planet.";
      String stemmed = ps.stem_document(text);
      expect(stemmed, "the young botanist wa fascin by the collect of plant she had gather dure her research expedit . observ the natur variat within differ plant speci , she note that mani characterist were evolv uniqu , and she hypothes that environment chang were contribut significantli . by compar divers specimen , she aim to better understand the relationship between evolut , adapt , and biodivers . analyz the development pathwai of each plant , she began categor them base on similar attribut . her colleagu , equal intrigu , assist by meticul document each observ , ensur that all inform wa preserv accur for futur refer . thei believ their collabor effort would eventu enhanc the understand of botan scienc , lead to potenti breakthrough in agricultur sustain . throughout the process , thei also consid the broader implic of their work , ponder how their find could influenc climat chang polici . the potenti applic of their research seem vast , stretch from educ commun to rethink agricultur practic that were unsustain . their motiv wa driven not onli by scientif curios but also by a profound sens of respons for preserv ecolog balanc . the expedit had it challeng , of cours . dai were spent endur extrem weather condit , hike through dens underbrush , and navig tricki terrain . each encount with the natur world brought forth it own set of difficulti , yet the botanist and her team remain undet . everi new discoveri , whether it wa a previous unknown fungu or a plant displai an unusu pattern of growth , reignit their determin . as their journei continu , thei compil a vast repositori of inform . thi collect becam a valuabl databas that could potenti aid other scientist in address question about speci distribut , resili , and adapt in the face of environment pressur . thei envis a futur where the fruit of their labor would inspir new gener of research to approach the natur world with a similar blend of curios and rever . ultim , the botanist believ that the most meaning contribut thei could make wa to foster an understand of how interconnect all live system were . she hope that their expedit , despit it hardship , would plant the seed of knowledg that could help societi navig an uncertain ecolog futur . their work emphas the import of resili , adapt , and inform stewardship of the environ , which thei saw as essenti for the long-term health of our planet .");
    });
    test("Test 2", () {
      PorterStemmer ps = PorterStemmer();
      String text = "The atmospheric conditions drastically affected the agricultural productivity in various regions, leading to significant alterations in the landscape. Farmers were strategizing to combat the increasingly unpredictable weather patterns, as the traditional approaches were no longer sufficient. Their continuous struggle demonstrated resilience, but they needed a more systematic intervention to address the multifaceted challenges. Utilizing technological advancements, the agricultural sector aimed to develop a sustainable model that integrated innovative practices with ecological principles. Scientists collaborated to enhance crop resilience, focusing on genetic modifications and optimizing resource utilization. Their experiments yielded promising results, indicating a potential for breakthrough solutions to address food scarcity globally. Despite the arduous conditions, there was a prevailing sense of optimism, believing that the collaborative efforts of various sectors would contribute to a more secure and resilient food system for the future.";
      String stemmed = ps.stem_document(text);
      expect(stemmed, "the atmospher condit drastic affect the agricultur product in variou region , lead to signific alter in the landscap . farmer were strateg to combat the increasingli unpredict weather pattern , as the tradit approach were no longer suffici . their continu struggl demonstr resili , but thei need a more systemat intervent to address the multifacet challeng . util technolog advanc , the agricultur sector aim to develop a sustain model that integr innov practic with ecolog principl . scientist collabor to enhanc crop resili , focus on genet modif and optim resourc util . their experi yield promis result , indic a potenti for breakthrough solut to address food scarciti global . despit the arduou condit , there wa a prevail sens of optim , believ that the collabor effort of variou sector would contribut to a more secur and resili food system for the futur .");
    });
    test("Test 3", () {
      PorterStemmer ps = PorterStemmer();
      String text = "The evolutionary journey of civilization has witnessed various monumental developments, each one contributing to the tapestry of modern society. The industrialization of the nineteenth century brought about tremendous economic growth, facilitating urban expansion and transforming the livelihoods of countless individuals. Nevertheless, these advancements were not without their drawbacks, as the exploitation of natural resources accelerated environmental degradation. Governments, realizing the importance of sustainability, began formulating policies to mitigate the detrimental effects of industrial activities. Meanwhile, scientists were meticulously investigating the complex interdependencies within ecosystems, aiming to preserve biodiversity and restore habitats that had been critically damaged. Simultaneously, technological advancements in the latter half of the twentieth century fostered innovations in communication, leading to the globalization of cultures, economies, and ideologies. These shifts necessitated the adaptation of social institutions, and educators were tasked with preparing younger generations for a rapidly changing world. Educational systems evolved to emphasize critical thinking, collaboration, and creativity, which were seen as essential skills for navigating an increasingly interconnected and automated society. On a parallel front, healthcare systems also experienced transformations. The discovery of antibiotics and the advancement of medical procedures prolonged human lifespan and improved the quality of life. However, the emergence of antibiotic resistance presented new challenges, requiring a re-evaluation of medical protocols and a focus on preventive measures to maintain public health. In recent years, attention has also shifted toward mental well-being, recognizing the intricate link between mental health and overall wellness. Psychological research has led to a better understanding of the factors contributing to mental disorders, while public awareness campaigns have aimed to reduce the stigma surrounding mental health issues. Despite the numerous challenges, there has been a growing recognition of the interconnected nature of societal issues. Climate change, economic inequality, and political instability are no longer viewed in isolation but are seen as components of a complex global network that requires cooperative problem-solving strategies. Activists, scientists, and policymakers have come together to advocate for comprehensive approaches that integrate social, environmental, and economic perspectives, striving for a holistic and sustainable future. The resilience and ingenuity of humanity have been the driving forces behind overcoming adversity, and there is optimism that, through innovation and collaboration, a more equitable and prosperous world can be achieved.";
      String stemmed = ps.stem_document(text);
      expect(stemmed, "the evolutionari journei of civil ha wit variou monument develop , each on contribut to the tapestri of modern societi . the industri of the nineteenth centuri brought about tremend econom growth , facilit urban expans and transform the livelihood of countless individu . nevertheless , these advanc were not without their drawback , as the exploit of natur resourc acceler environment degrad . govern , realiz the import of sustain , began formul polici to mitig the detriment effect of industri activ . meanwhil , scientist were meticul investig the complex interdepend within ecosystem , aim to preserv biodivers and restor habitat that had been critic damag . simultan , technolog advanc in the latter half of the twentieth centuri foster innov in commun , lead to the global of cultur , economi , and ideolog . these shift necessit the adapt of social institut , and educ were task with prepar younger gener for a rapidli chang world . educ system evolv to emphas critic think , collabor , and creativ , which were seen as essenti skill for navig an increasingli interconnect and autom societi . on a parallel front , healthcar system also experienc transform . the discoveri of antibiot and the advanc of medic procedur prolong human lifespan and improv the qualiti of life . howev , the emerg of antibiot resist present new challeng , requir a re-evalu of medic protocol and a focu on prevent measur to maintain public health . in recent year , attent ha also shift toward mental well-b , recogn the intric link between mental health and overal well . psycholog research ha led to a better understand of the factor contribut to mental disord , while public awar campaign have aim to reduc the stigma surround mental health issu . despit the numer challeng , there ha been a grow recognit of the interconnect natur of societ issu . climat chang , econom inequ , and polit instabl ar no longer view in isol but ar seen as compon of a complex global network that requir cooper problem-solv strategi . activist , scientist , and policymak have come togeth to advoc for comprehens approach that integr social , environment , and econom perspect , strive for a holist and sustain futur . the resili and ingenu of human have been the drive forc behind overcom advers , and there is optim that , through innov and collabor , a more equit and prosper world can be achiev .");
    });
  });
}